name: Deploy Python app to Azure Web App

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 必要ならテストやビルドをここに追加

      - name: Zip artifact
        run: |
          mkdir -p ./artifact
          zip -r ./artifact/app.zip . -x "*.git*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "<あなたの Azure Web App 名>"   # 例: linkfastnect-backend
          package: "./artifact/app.zip"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
